"""
download_products.py
====================
Sentinel-1 SLC product download via Copernicus Data Space S3 endpoint.

Reads the SBAS pairs list generated by sbas_search.py and downloads
all unique Sentinel-1 SLC products organised by flight direction.

Features:
    - Per-file progress bar with download speed (MB/s)
    - File-existence check: skips products already present on disk.
    - Copernicus S3 path construction from product ID.
    - Ascending / descending folder separation.
    - Download log saved to JSON.
    - Configurable output directory via DOWNLOAD_DIR or CLI.

Dependencies:
    pip install boto3 pandas tqdm python-dotenv

Credentials:
    Register at https://dataspace.copernicus.eu
    Then export or set in .env:
        COPERNICUS_ACCESS_KEY=your_access_key
        COPERNICUS_SECRET_KEY=your_secret_key
"""

import logging
import os
import json
import subprocess
import time
import re
import threading
from pathlib import Path

from dotenv import load_dotenv
load_dotenv(override=True)

import boto3
import pandas as pd
from tqdm import tqdm

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)

# ─────────────────────────────────────────────
# CONFIGURATION
# ─────────────────────────────────────────────

S3_ENDPOINT = "https://eodata.dataspace.copernicus.eu"
S3_BUCKET   = "eodata"

ACCESS_KEY = os.environ.get("COPERNICUS_ACCESS_KEY", "")
SECRET_KEY = os.environ.get("COPERNICUS_SECRET_KEY", "")

PAIRS_CSV     = os.path.join("outputs", "sbas_pairs.csv")
PRODUCTS_JSON = os.path.join("outputs", "products_metadata.json")
DOWNLOAD_DIR  = os.path.join("outputs", "slc_products")
DOWNLOAD_LOG  = os.path.join("outputs", "download_log.json")


# ─────────────────────────────────────────────
# S3 PATH CONSTRUCTION
# ─────────────────────────────────────────────

def build_s3_prefix(scene_name: str):
    clean = scene_name.replace(".SAFE", "").strip()
    match = re.search(r"_(\d{8}T\d{6})_", clean)
    if not match:
        logger.warning("Cannot extract date from scene: %s", scene_name)
        return None
    start_time = match.group(1)
    year  = start_time[0:4]
    month = start_time[4:6]
    day   = start_time[6:8]
    return f"Sentinel-1/SAR/IW_SLC__1S/{year}/{month}/{day}/{clean}.SAFE/"


# ─────────────────────────────────────────────
# ASF FALLBACK DOWNLOAD
# ─────────────────────────────────────────────

def download_from_asf(scene_name, flight_dir, target_dir, session=None):
    """
    Download a single Sentinel-1 SLC scene from ASF (Alaska Satellite Facility).

    Used as fallback when Copernicus S3 returns no objects — which happens
    for data older than ~12 months (not kept online by Copernicus).

    Requires NASA Earthdata credentials in ~/.netrc:
        machine urs.earthdata.nasa.gov login YOUR_USER password YOUR_PASS
    """
    try:
        import asf_search as asf
    except ImportError:
        logger.error("asf_search not installed — run: pip install asf_search")
        return None

    subfolder  = os.path.join(target_dir, flight_dir)
    local_path = os.path.join(subfolder, scene_name)
    os.makedirs(local_path, exist_ok=True)

    try:
        results = asf.granule_search([scene_name])
        if not results:
            logger.warning("  ASF: scene not found: %s", scene_name)
            return None

        logger.info("  ASF download: %s", scene_name)

        if session is None:
            token = os.environ.get("NASA_EARTHDATA_TOKEN", "")
            if token:
                session = asf.ASFSession().auth_with_token(token)
                logger.info("  ASF auth: token from NASA_EARTHDATA_TOKEN env var")
            else:
                import netrc
                try:
                    n = netrc.netrc()
                    creds = n.authenticators("urs.earthdata.nasa.gov")
                    if creds:
                        pw = creds[2]
                        if len(pw) > 50:  # JWT token stored as password
                            session = asf.ASFSession().auth_with_token(pw)
                            logger.info("  ASF auth: token from ~/.netrc")
                        else:
                            session = asf.ASFSession().auth_with_creds(creds[0], pw)
                            logger.info("  ASF auth: credentials from ~/.netrc")
                    else:
                        raise ValueError("No earthdata entry in ~/.netrc")
                except Exception as e:
                    logger.error("ASF auth failed: %s", e)
                    logger.error("Set NASA_EARTHDATA_TOKEN=your_jwt_token")
                    return None

        results.download(path=subfolder, session=session, processes=1)

        # asf_search downloads as .zip — check it arrived
        zip_file = os.path.join(subfolder, scene_name + ".zip")
        safe_dir = os.path.join(subfolder, scene_name + ".SAFE")
        if os.path.isfile(zip_file):
            logger.info("  ASF: extracting %s.zip ...", scene_name)
            import zipfile
            with zipfile.ZipFile(zip_file, "r") as z:
                z.extractall(subfolder)
            os.remove(zip_file)
            return safe_dir if os.path.isdir(safe_dir) else local_path
        elif os.path.isdir(os.path.join(subfolder, scene_name)):
            return local_path
        else:
            logger.warning("  ASF: could not find extracted directory for %s", scene_name)
            return None

    except Exception as e:
        logger.error("  ASF download failed for %s: %s", scene_name, e)
        return None


# ─────────────────────────────────────────────
# DEM DOWNLOAD
# ─────────────────────────────────────────────

def download_dem(aoi: dict, output_dir: str, dem_name: str = "dem_merged.hgt") -> str:
    """
    Download and stitch SRTM 1-arcsec DEM tiles covering the AOI using ISCE2 dem.py.

    Args:
        aoi:        {"min_lat", "max_lat", "min_lon", "max_lon"}
        output_dir: directory to save the DEM (e.g. /home/pc/Mining_work/dem)
        dem_name:   output filename (default: dem_merged.hgt)

    Returns:
        Absolute path to the DEM file, or None on failure.

    Notes:
        - Uses JPL mirror (aria-alt-dav.jpl.nasa.gov) which is more reliable
          than the default NASA SRTM server (e4ftl01.cr.usgs.gov).
        - Applies EGM96→WGS84 geoid correction (-c flag).
        - Requires NASA Earthdata credentials in ~/.netrc.
    """
    import math

    os.makedirs(output_dir, exist_ok=True)
    dem_path = os.path.join(output_dir, dem_name)

    if os.path.isfile(dem_path):
        logger.info("DEM already exists: %s", dem_path)
        return dem_path

    # Expand bbox by 0.1° margin to ensure full coverage
    south = int(math.floor(aoi["min_lat"])) - 1
    north = int(math.ceil(aoi["max_lat"])) + 1
    west  = int(math.floor(aoi["min_lon"])) - 1
    east  = int(math.ceil(aoi["max_lon"])) + 1

    logger.info(
        "Downloading SRTM DEM: bbox=[%d %d %d %d] → %s",
        south, north, west, east, dem_path
    )

    # Try JPL mirror first (more reliable for older data)
    mirrors = [
        "https://aria-alt-dav.jpl.nasa.gov/repository/products/SRTM1_v3/",
        "",  # default NASA server
    ]

    # Get NASA credentials from netrc
    nasa_user, nasa_pass = "", ""
    try:
        import netrc as netrc_module
        n = netrc_module.netrc()
        creds = n.authenticators("urs.earthdata.nasa.gov")
        if creds:
            nasa_user = creds[0]
            nasa_pass = creds[2]
    except Exception:
        pass

    for mirror in mirrors:
        cmd = [
            "dem.py",
            "-a", "stitch",
            "-b", str(south), str(north), str(west), str(east),
            "-s", "1",          # 1 arcsec resolution
            "-r",               # report downloads
            "-c",               # EGM96 → WGS84 correction
            "-o", dem_path,
            "-d", output_dir,
        ]
        if mirror:
            cmd += ["-u", mirror]
        if nasa_user:
            cmd += ["-n", nasa_user, "-w", nasa_pass]

        logger.info("  Trying DEM source: %s", mirror or "default NASA server")
        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                timeout=300,
                cwd=output_dir,
            )
            if result.returncode == 0 and os.path.isfile(dem_path):
                size_mb = os.path.getsize(dem_path) / 1024 / 1024
                logger.info("DEM downloaded ✅  %.1f MB → %s", size_mb, dem_path)
                return dem_path
            else:
                stderr = result.stderr.decode()
                if "missing" in stderr.lower() or "failed" in stderr.lower():
                    logger.warning("  DEM download failed from this mirror: %s", stderr[:200])
                    continue
        except subprocess.TimeoutExpired:
            logger.warning("  DEM download timed out for mirror: %s", mirror)
            continue
        except FileNotFoundError:
            logger.error("dem.py not found — is ISCE2 on PATH?")
            return None

    # If still failed, try downloading tiles directly and stitching manually
    logger.warning("All DEM mirrors failed — trying tile-by-tile download ...")
    return _download_dem_tiles(aoi, output_dir, dem_path, nasa_user, nasa_pass)


def _download_dem_tiles(aoi, output_dir, dem_path, nasa_user="", nasa_pass=""):
    """
    Fallback: download individual SRTM tiles and stitch with GDAL.
    Covers cases where dem.py fails due to server issues.
    """
    import math, struct

    south = int(math.floor(aoi["min_lat"]))
    north = int(math.ceil(aoi["max_lat"]))
    west  = int(math.floor(aoi["min_lon"]))
    east  = int(math.ceil(aoi["max_lon"]))

    tile_paths = []
    base_urls = [
        "https://aria-alt-dav.jpl.nasa.gov/repository/products/SRTM1_v3/",
        "https://e4ftl01.cr.usgs.gov/MEASURES/SRTMGL1.003/2000.02.11/",
    ]

    for lat in range(south, north):
        for lon in range(west, east):
            ns  = "N" if lat >= 0 else "S"
            ew  = "E" if lon >= 0 else "W"
            fn  = f"{ns}{abs(lat):02d}{ew}{abs(lon):03d}.SRTMGL1.hgt.zip"
            out = os.path.join(output_dir, fn)

            if os.path.isfile(out.replace(".zip", "")):
                tile_paths.append(out.replace(".zip", ""))
                continue

            downloaded = False
            for base_url in base_urls:
                url = base_url + fn
                cmd = ["wget", "-q", "--show-progress",
                       "-O", out, url]
                if nasa_user:
                    cmd += ["--user", nasa_user, "--password", nasa_pass]

                try:
                    r = subprocess.run(cmd, capture_output=True, timeout=120)
                    if r.returncode == 0 and os.path.isfile(out):
                        # Unzip
                        subprocess.run(["unzip", "-q", "-o", out, "-d", output_dir],
                                       capture_output=True)
                        hgt = out.replace(".zip", "")
                        if os.path.isfile(hgt):
                            tile_paths.append(hgt)
                            downloaded = True
                            break
                except Exception:
                    continue

            if not downloaded:
                logger.warning("Could not download tile: %s", fn)

    if not tile_paths:
        logger.error("No DEM tiles downloaded")
        return None

    if len(tile_paths) == 1:
        import shutil
        shutil.copy2(tile_paths[0], dem_path)
        return dem_path

    # Merge tiles with GDAL
    vrt = dem_path + ".vrt"
    r = subprocess.run(
        ["gdalbuildvrt", vrt] + tile_paths,
        capture_output=True
    )
    if r.returncode == 0:
        subprocess.run(
            ["gdal_translate", "-of", "ENVI", "-ot", "Int16", vrt, dem_path],
            capture_output=True
        )
        if os.path.isfile(dem_path):
            logger.info("DEM stitched from %d tiles ✅", len(tile_paths))
            return dem_path

    logger.error("DEM tile stitching failed")
    return None


# ─────────────────────────────────────────────
# EXISTENCE CHECK
# ─────────────────────────────────────────────

def product_already_downloaded(local_path: str) -> bool:
    if not os.path.exists(local_path):
        return False
    all_files = []
    for _, _, files in os.walk(local_path):
        all_files.extend(files)
    has_data = any(f.endswith((".tiff", ".xml", ".EOF", ".safe")) for f in all_files)
    if has_data:
        logger.info("  Already downloaded (skipping): %s", local_path)
        return True
    return False


# ─────────────────────────────────────────────
# PROGRESS CALLBACK
# ─────────────────────────────────────────────

class ProgressCallback:
    """
    boto3 transfer callback that updates a tqdm bar with
    bytes transferred and live download speed.
    """
    def __init__(self, bar: tqdm, total_bytes: int):
        self._bar        = bar
        self._transferred = 0
        self._lock       = threading.Lock()
        self._start      = time.time()
        self._bar.total  = total_bytes
        self._bar.reset()

    def __call__(self, bytes_amount: int):
        with self._lock:
            self._transferred += bytes_amount
            elapsed = time.time() - self._start or 0.001
            speed_mb = (self._transferred / elapsed) / (1024 * 1024)
            self._bar.update(bytes_amount)
            self._bar.set_postfix_str(f"{speed_mb:.2f} MB/s", refresh=True)


# ─────────────────────────────────────────────
# SINGLE PRODUCT DOWNLOAD
# ─────────────────────────────────────────────

def download_single_product(
    s3_resource,
    scene_name: str,
    flight_dir: str,
    target_dir: str,
):
    subfolder  = os.path.join(target_dir, flight_dir)
    local_path = os.path.join(subfolder, scene_name)

    if product_already_downloaded(local_path):
        return local_path

    os.makedirs(local_path, exist_ok=True)

    prefix = build_s3_prefix(scene_name)
    if not prefix:
        logger.error("  Could not build S3 prefix for: %s", scene_name)
        return None

    logger.info("  S3 prefix : %s", prefix)

    bucket  = s3_resource.Bucket(S3_BUCKET)
    objects = list(bucket.objects.filter(Prefix=prefix))

    if not objects:
        logger.warning("  No S3 objects found for prefix: %s", prefix)
        logger.info("  Trying ASF fallback download (older data not on Copernicus S3) ...")
        return download_from_asf(scene_name, flight_dir, target_dir)

    # Calculate total size
    total_bytes = sum(obj.size for obj in objects)
    total_mb    = total_bytes / (1024 * 1024)
    logger.info(
        "  Downloading %s  (%d files, %.0f MB) ...",
        scene_name, len(objects), total_mb
    )

    downloaded_count = 0
    with tqdm(
        total=total_bytes,
        unit="B",
        unit_scale=True,
        unit_divisor=1024,
        desc=f"  {scene_name[:40]}",
        leave=False,
        dynamic_ncols=True,
    ) as byte_bar:
        callback = ProgressCallback(byte_bar, total_bytes)

        for obj in objects:
            rel_path  = obj.key[len(prefix):]
            if not rel_path:
                continue
            file_path = os.path.join(local_path, rel_path)
            os.makedirs(os.path.dirname(file_path), exist_ok=True)

            try:
                bucket.download_file(
                    obj.key,
                    file_path,
                    Callback=callback,
                )
                downloaded_count += 1
            except Exception as exc:
                logger.warning("    Error downloading %s: %s", rel_path, exc)

    elapsed_min = (time.time() - callback._start) / 60
    avg_speed   = (total_bytes / (1024 * 1024)) / (elapsed_min * 60 or 1)
    logger.info(
        "  ✅ Done: %d files  %.0f MB  %.1f min  avg %.2f MB/s  → %s",
        downloaded_count, total_mb, elapsed_min, avg_speed, local_path
    )
    return local_path


# ─────────────────────────────────────────────
# COLLECT UNIQUE SCENES
# ─────────────────────────────────────────────

def collect_unique_scenes(pairs_csv: str) -> list:
    try:
        df = pd.read_csv(pairs_csv)
    except Exception:
        logger.warning("sbas_pairs.csv is empty or missing — nothing to download.")
        return []

    if df.empty or "reference_scene" not in df.columns:
        logger.warning("sbas_pairs.csv has no valid pairs — nothing to download.")
        return []

    ref = df[["reference_scene"]].rename(columns={"reference_scene": "scene_name"})
    sec = df[["secondary_scene"]].rename(columns={"secondary_scene": "scene_name"})

    unique = (
        pd.concat([ref, sec], ignore_index=True)
        .drop_duplicates(subset="scene_name")
        .to_dict("records")
    )
    logger.info("Unique scenes to download: %d", len(unique))
    return unique


# ─────────────────────────────────────────────
# LOAD FLIGHT DIRECTIONS
# ─────────────────────────────────────────────

def load_flight_directions(products_json: str) -> dict:
    if not os.path.exists(products_json):
        logger.warning("products_metadata.json not found — scenes go to /unknown")
        return {}
    with open(products_json) as f:
        records = json.load(f)
    return {
        r["scene_name"]: r.get("flight_dir", "unknown").lower()
        for r in records
    }


# ─────────────────────────────────────────────
# BATCH DOWNLOAD
# ─────────────────────────────────────────────

def run_download(scenes, flight_dirs, s3_resource, download_dir) -> list:
    log = []
    bar = tqdm(total=len(scenes), desc="Scenes", unit="scene", position=0)

    for scene in scenes:
        name      = scene["scene_name"]
        direction = flight_dirs.get(name, "unknown")
        bar.set_description(f"Scene: {name[:30]}")

        try:
            local_path = download_single_product(
                s3_resource, name, direction, download_dir
            )
            status = "success" if local_path else "failed"
            entry  = {"scene": name, "status": status}
            if local_path:
                entry["path"] = local_path
            log.append(entry)
        except Exception as exc:
            log.append({"scene": name, "status": "failed", "reason": str(exc)})
            logger.error("Error for %s: %s", name, exc)

        bar.update(1)
        time.sleep(0.3)

    bar.close()
    return log


# ─────────────────────────────────────────────
# SUMMARY
# ─────────────────────────────────────────────

def print_summary(log) -> None:
    statuses = [e["status"] for e in log]
    print("\n" + "=" * 50)
    print("  DOWNLOAD SUMMARY")
    print("=" * 50)
    print(f"  Total scenes  : {len(log)}")
    print(f"  Success       : {statuses.count('success')}")
    print(f"  Already exist : {statuses.count('already_exists')}")
    print(f"  Failed        : {statuses.count('failed')}")
    print("=" * 50 + "\n")


# ─────────────────────────────────────────────
# SAVE OUTPUTS
# ─────────────────────────────────────────────

def save_log(log, log_path: str) -> None:
    with open(log_path, "w") as f:
        json.dump(log, f, indent=2)
    logger.info("Download log saved -> %s", log_path)


def copy_pairs_alongside_products(pairs_csv: str, download_dir: str) -> None:
    import shutil
    dest = os.path.join(download_dir, "sbas_pairs.csv")
    shutil.copy2(pairs_csv, dest)
    logger.info("Pairs CSV copied -> %s", dest)


# ─────────────────────────────────────────────
# MAIN (called by main_v3.py or standalone)
# ─────────────────────────────────────────────

def main(download_dir: str = None, aoi: dict = None, dem_output_dir: str = None):
    if not ACCESS_KEY or not SECRET_KEY:
        raise EnvironmentError(
            "Copernicus Data Space credentials not set.\n"
            "Register for free at: https://dataspace.copernicus.eu\n\n"
            "Then set in .env file or export in terminal:\n"
            "  export COPERNICUS_ACCESS_KEY=your_access_key\n"
            "  export COPERNICUS_SECRET_KEY=your_secret_key"
        )

    target_dir = download_dir or DOWNLOAD_DIR
    os.makedirs(os.path.join(target_dir, "ascending"),  exist_ok=True)
    os.makedirs(os.path.join(target_dir, "descending"), exist_ok=True)
    os.makedirs(os.path.join(target_dir, "unknown"),    exist_ok=True)
    logger.info("Download directory: %s", os.path.abspath(target_dir))

    # Auto-download DEM if AOI provided
    if aoi and dem_output_dir:
        dem_path = download_dem(aoi, dem_output_dir)
        if dem_path:
            logger.info("DEM ready: %s", dem_path)
        else:
            logger.warning("DEM download failed — ISCE2 will need a manual DEM path")

    logger.info("Connecting to Copernicus Data Space S3 ...")
    session = boto3.session.Session()
    s3 = session.resource(
        "s3",
        endpoint_url          = S3_ENDPOINT,
        aws_access_key_id     = ACCESS_KEY,
        aws_secret_access_key = SECRET_KEY,
        region_name           = "default",
    )

    scenes      = collect_unique_scenes(PAIRS_CSV)
    flight_dirs = load_flight_directions(PRODUCTS_JSON)

    if not scenes:
        logger.warning("No scenes to download.")
        return

    log = run_download(scenes, flight_dirs, s3, target_dir)

    copy_pairs_alongside_products(PAIRS_CSV, target_dir)
    save_log(log, DOWNLOAD_LOG)
    print_summary(log)

    logger.info("SLC products ready at: %s", os.path.abspath(target_dir))


if __name__ == "__main__":
    import argparse
    p = argparse.ArgumentParser()
    p.add_argument("--download-dir", default=None,
                   help="Root download directory (default: outputs/slc_products)")
    args = p.parse_args()
    main(download_dir=args.download_dir)